---
include:
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: reset

  - board: nice_nano_v2
    shield: prototype_mk1_dongle oled_adapter_pro_micro_128x32
    artifact-name: center-dongle
    cmake-args: -DCONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=n -DCONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y

  - board: nice_nano_v2
    shield: prototype_mk1_left nice_view_adapter nice_view_gem
    artifact-name: left-dongle

  - board: nice_nano_v2
    shield: prototype_mk1_left nice_view_adapter nice_view_gem
    artifact-name: left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_NICE_VIEW_ANIMATION_THEME_TRANSMUTATION=y

  - board: nice_nano_v2
    shield: prototype_mk1_right nice_view_adapter nice_view_gem
    artifact-name: right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_NICE_VIEW_ANIMATION_THEME_TRANSMUTATION=y


