---
include:
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: reset

  - board: nice_nano_v2
    shield: prototype_mk1_dongle oled_adapter_pro_micro_128x32
    artifact-name: center-dongle
    cmake-args: -DCONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=n -DCONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y

  - board: nice_nano_v2
    shield: prototype_mk1_left nice_view_adapter nice_view_gem
    artifact-name: left-dongle




  - board: nice_nano_v2
    shield: prototype_mk1_left nice_view_adapter nice_view_gem
    artifact-name: left_transmutation
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_NICE_VIEW_ANIMATION_THEME_TRANSMUTATION=y
  - board: nice_nano_v2
    shield: prototype_mk1_right nice_view_adapter nice_view_gem
    artifact-name: right_transmutation
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_NICE_VIEW_ANIMATION_THEME_TRANSMUTATION=y

  - board: nice_nano_v2
    shield: prototype_mk1_left nice_view_adapter nice_view_gem
    artifact-name: left_omnissiah
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_NICE_VIEW_ANIMATION_THEME_OMNISSIAH=y
  - board: nice_nano_v2
    shield: prototype_mk1_right nice_view_adapter nice_view_gem
    artifact-name: right_omnissiah
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_NICE_VIEW_ANIMATION_THEME_OMNISSIAH=y

  - board: nice_nano_v2
    shield: prototype_mk1_left nice_view_adapter nice_view_gem
    artifact-name: left_ultramar
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_NICE_VIEW_ANIMATION_THEME_ULTRAMAR=y
  - board: nice_nano_v2
    shield: prototype_mk1_right nice_view_adapter nice_view_gem
    artifact-name: right_ultramar
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_NICE_VIEW_ANIMATION_THEME_ULTRAMAR=y

  - board: nice_nano_v2
    shield: prototype_mk1_left nice_view_adapter nice_view_gem
    artifact-name: left_crystal
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_NICE_VIEW_ANIMATION_THEME_CRYSTAL=y
  - board: nice_nano_v2
    shield: prototype_mk1_right nice_view_adapter nice_view_gem
    artifact-name: right_crystal
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_NICE_VIEW_ANIMATION_THEME_CRYSTAL=y


