---
include:
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: reset

  - board: nice_nano_v2
    shield: prototype_mk1_dongle oled_adapter_pro_micro_128x32
    artifact-name: center-dongle
    cmake-args: -DCONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=n -DCONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y

  - board: nice_nano_v2
    shield: prototype_mk1_left nice_view_adapter nice_view_gem
    artifact-name: left-dongle

  - board: nice_nano_v2
    shield: prototype_mk1_left nice_view_adapter nice_view_gem
    artifact-name: left_TRANSMUTATION
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_NICE_VIEW_ANIMATION_THEME='0'

  - board: nice_nano_v2
    shield: prototype_mk1_right nice_view_adapter nice_view_gem
    artifact-name: right_TRANSMUTATION
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_NICE_VIEW_ANIMATION_THEME='0'

  - board: nice_nano_v2
    shield: prototype_mk1_left nice_view_adapter nice_view_gem
    artifact-name: left_OMNISSIAH
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_NICE_VIEW_ANIMATION_THEME=1

  - board: nice_nano_v2
    shield: prototype_mk1_right nice_view_adapter nice_view_gem
    artifact-name: right_OMNISSIAH
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_NICE_VIEW_ANIMATION_THEME=1

  - board: nice_nano_v2
    shield: prototype_mk1_left nice_view_adapter nice_view_gem
    artifact-name: left_ULTRAMAR
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_NICE_VIEW_ANIMATION_THEME=2

  - board: nice_nano_v2
    shield: prototype_mk1_right nice_view_adapter nice_view_gem
    artifact-name: right_ULTRAMAR
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_NICE_VIEW_ANIMATION_THEME=2

  - board: nice_nano_v2
    shield: prototype_mk1_left nice_view_adapter nice_view_gem
    artifact-name: left_CRYSTAL
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_NICE_VIEW_ANIMATION_THEME=3

  - board: nice_nano_v2
    shield: prototype_mk1_right nice_view_adapter nice_view_gem
    artifact-name: right_CRYSTAL
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_NICE_VIEW_ANIMATION_THEME=3





